batch_size: 32
d_head: 32
d_inner: 4096
d_model: 1024
dropout: 0.2
dropatt: 0.0
embed_size: 256
epochs: 1771
learning_rate: 0.00001
n_head: 32
n_encoder_layer: 4
n_decoder_layer: 2
noise_schedule: "cosine"
noise_steps: 1000
overlap: 0
position_weight: 0.01
representation: "6dof"
rotation_weight: 1
scalar_type: "standard"
scale: true
seq_length: 90
time_embd_dim: 32
velocity_weight: 0.5
acceleration_weight: 0.5
kinetic_weight: 0.2
mem_len: 180
weight_decay: 0.01
speaker_emb_size: 8
train_data_path: "data/train"
val_data_path: "data/val"
test_data_path: "data/test"
model_name: "ueadh"